### ISSUE TITLE
some error occured

### ISSUE THREAD

**Issue by jhj7905** [juangallostra/augmented-reality#2]
hi @juangallostra 
when i ran your code, then error occured like below

[ INFO:0] Initialize OpenCL runtime...
Traceback (most recent call last):
  File "src/ar_main.py", line 174, in <module>
    main()
  File "src/ar_main.py", line 40, in main
    obj = OBJ(os.path.join(dir_name, 'models/cow.obj'), swapyz=True)
  File "/home/hyunjo/Face_Detection/augmented-reality/src/objloader_simple.py", line 16, in __init__
    v = v[0], v[2], v[1]
TypeError: 'map' object is not subscriptable

can you tell me how to fix it ?
in advance, thank you

**Comment by jhj7905** [comment]
@juangallostra 
it was related to problem of version
i fixed it like list(map ~~)

**Comment by juangallostra** [comment]
@jhj7905 yeah, the problem is that in Python 3 `map` returns an iterable object of type map, and not a subscriptible list. Glad you found the solution!
