### ISSUE TITLE
Dimensions of a card

### ISSUE THREAD

**Issue by peethamber** [juangallostra/augmented-reality#5]
Hi,
The code is great. While running this the issue I am facing is the objects keep jumping around and do not stay on the reference surface. I am using the webcam. I am i doing something wrong. I am still not sure if the dimensions of the card or the surface of the card is the problem. Kindly let me know.

**Comment by juangallostra** [comment]
@peethamber Dimensions should not be an issue. Just to make sure, did you add an image (in jpg format) of the visiting card under the `reference` folder and named it `model.jpg`?

If so, the problem could be that the visiting card you are using as a reference doesn't have enough singular points and hence no correspondences are found.You can try using a different card to see if that makes any difference.

**Comment by peethamber** [comment]
Thanks. I got it to work. I will close.

**Comment by anujchoudhury** [comment]
peethamber, how did you solve the issue of objects jumping around ?
