### ISSUE TITLE
Size of loaded model and textures

### ISSUE THREAD

**Issue by ShubhamJain7** [juangallostra/augmented-reality#6]
I tried loading a few models of my own but the loaded models are extremely tiny while models you have provided are of the perfect size. Is there any way to overcome this? Also, how do you go about loading textures?

Attaching a model that has this issue:
[dna.zip](https://github.com/juangallostra/augmented-reality/files/2721185/dna.zip)

**Comment by ShubhamJain7** [comment]
Trying to implement my own texture loader would be a big detour for what I am trying to achieve. Think I will try and get it done with OpenGL itself.

**Comment by juangallostra** [comment]
@ShubhamJain7 should we close the issue then?

**Comment by ShubhamJain7** [comment]
@juangallostra yes. I shall make a pull request if I am able to load textures.
