### ISSUE TITLE
Matching more than one object simultaneously

### ISSUE THREAD

**Issue by ShubhamJain7** [juangallostra/augmented-reality#7]
I want to be able to match more than a single reference object in the captured frames without any serious lags. I'm guessing threading is the way to go but still am unsure about how to go about it and match a reference object with the 3d model to be rendered.

**Comment by juangallostra** [comment]
@ShubhamJain7 correct me if I'm wrong but, if I understand correctly, what you want to do is have more than one pair of (reference, model) and match and render all of them in the same frame isn't it?

**Comment by ShubhamJain7** [comment]
Yes, exactly!

**Comment by juangallostra** [comment]
@ShubhamJain7 to achieve so you will have to, for each reference, model pair:
1. Load reference and model and keep track that those two go together (maybe using a `dict` or by creating a class):
https://github.com/juangallostra/augmented-reality/blob/19a49c47982df9009c7f6ec06a0eb3613050562b/src/ar_main.py#L36
https://github.com/juangallostra/augmented-reality/blob/19a49c47982df9009c7f6ec06a0eb3613050562b/src/ar_main.py#L40
2. Compute reference surface keypoints and descriptors:
https://github.com/juangallostra/augmented-reality/blob/19a49c47982df9009c7f6ec06a0eb3613050562b/src/ar_main.py#L38
3. Match reference surface keypoints with frame keypoints, compute homography and render model:
https://github.com/juangallostra/augmented-reality/blob/19a49c47982df9009c7f6ec06a0eb3613050562b/src/ar_main.py#L50-L85

Some notes:
* You can reuse the ORB keypoint detector and BF matcher. There is no need to create new instances of them for each reference and model pair you want to include.

* I **think** a possible data structure you can use is a `tuple` of dicts like:
```python
models = (
    {'reference': model_1}, {'object': obj_1}, {'keypoints': (kp_model_1, des_model_1)}, # pair 1
    {'reference': model_2}, {'object': obj_2}, {'keypoints': (kp_model_2, des_model_2)}, # pair 2
)
```
where, for each pair, `model_x = cv2.imread(os.path.join(dir_name, 'reference/model.jpg'), 0)`, `obj_x = OBJ(os.path.join(dir_name, 'models/fox.obj'), swapyz=True) ` and `kp_model_x, des_model_x = orb.detectAndCompute(model, None)`. You can build this structure iteratively and later iterate over it to detect all surfaces and render all models.

**Comment by juangallostra** [comment]
When it comes to multi threading, I would have to spend some time on it to suggest a possible implementation.

**Comment by ShubhamJain7** [comment]
@juangallostra Thanks! I will give it a shot with multithreading.
